# Use Node base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY ../backend/package*.json ./
RUN npm install

# Copy the rest of the code
COPY ../backend .

# Expose backend port
EXPOSE 5000

# Start the backend
CMD ["npm", "start"]
