version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bookdb
    volumes:
      - mongo-data:/data/db
    networks:
      - booknet

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/bookdb
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - booknet

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Nginx serves on port 80 inside container
    depends_on:
      - backend
    networks:
      - booknet

volumes:
  mongo-data:

networks:
  booknet:
    driver: bridge
